services:
  - type: web
    name: staticlass-backend
    runtime: docker
    dockerfilePath: ./app/backend/Dockerfile
    dockerContext: ./app/backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: staticlass-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8080

databases:
  - name: staticlass-db
    databaseName: staticlass
    user: staticlass
    plan: free
